In [1]:
#for installing pandas
!pip install pandas

#import pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
data = {
    "car":["honda city","hyundai creta","maruti swift","tat nexon","toyota innova","honda amaze","kia seltos","maruti baleno"],
    "company":["honda","hyundai","maruti","tata","toyota","honda","kia","maruti"],
    "year":[2022,2023,2021,2023,2022,2020,2024,2021],
    "price":[1200000,1500000,700000,1100000,2200000,650000,1600000,800000],
    "mileage":[18,17,23,19,14,20,16,22],
    "Fuel":["petrol","disel","petrol","disel","disel","petrol","petrol","petrol"],
    "rating":[4.5,4.3,4.2,4.4,4.6,4.0,4.5,4.1]
}
df=pd.DataFrame(data)

In [3]:
df.head()

             car  company  year    price  mileage    Fuel  rating
0     honda city    honda  2022  1200000       18  petrol     4.5
1  hyundai creta  hyundai  2023  1500000       17   disel     4.3
2   maruti swift   maruti  2021   700000       23  petrol     4.2
3      tat nexon     tata  2023  1100000       19   disel     4.4
4  toyota innova   toyota  2022  2200000       14   disel     4.6

In [4]:
df.tail()

             car company  year    price  mileage    Fuel  rating
3      tat nexon    tata  2023  1100000       19   disel     4.4
4  toyota innova  toyota  2022  2200000       14   disel     4.6
5    honda amaze   honda  2020   650000       20  petrol     4.0
6     kia seltos     kia  2024  1600000       16  petrol     4.5
7  maruti baleno  maruti  2021   800000       22  petrol     4.1

In [7]:
df.shape

(8, 7)

In [8]:
df.columns

Index(['car', 'company', 'year', 'price', 'mileage', 'Fuel', 'rating'], dtype='object')

In [9]:
df.dtypes

car         object
company     object
year         int64
price        int64
mileage      int64
Fuel        object
rating     float64
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   car      8 non-null      object
 1   company  8 non-null      object
 2   year     8 non-null      int64
 3   price    8 non-null      int64
 4   mileage  8 non-null      int64
 5   Fuel     8 non-null      object
 6   rating   8 non-null      float64
dtypes: float64(1), int64(3), object(3)
memory usage: 580.0+ bytes

In [11]:
#select a single column
df["car"]

0       honda city
1    hyundai creta
2     maruti swift
3        tat nexon
4    toyota innova
5      honda amaze
6       kia seltos
7    maruti baleno
Name: car, dtype: object

In [12]:
df[["car","price"]]

             car    price
0     honda city  1200000
1  hyundai creta  1500000
2   maruti swift   700000
3      tat nexon  1100000
4  toyota innova  2200000
5    honda amaze   650000
6     kia seltos  1600000
7  maruti baleno   800000

In [13]:
#select rows using iloc
df.iloc[0:3]

             car  company  year    price  mileage    Fuel  rating
0     honda city    honda  2022  1200000       18  petrol     4.5
1  hyundai creta  hyundai  2023  1500000       17   disel     4.3
2   maruti swift   maruti  2021   700000       23  petrol     4.2

In [15]:
#select rows using iloc
df.loc[0:1]

             car  company  year    price  mileage    Fuel  rating
0     honda city    honda  2022  1200000       18  petrol     4.5
1  hyundai creta  hyundai  2023  1500000       17   disel     4.3

In [19]:
#filters car based on price
expensive_cars=df[df["price"]>1000000]
print(expensive_cars)

             car  company  year    price  mileage    Fuel  rating
0     honda city    honda  2022  1200000       18  petrol     4.5
1  hyundai creta  hyundai  2023  1500000       17   disel     4.3
3      tat nexon     tata  2023  1100000       19   disel     4.4
4  toyota innova   toyota  2022  2200000       14   disel     4.6
6     kia seltos      kia  2024  1600000       16  petrol     4.5

In [20]:
#sort car by price
sorted_cars=df.sort_values(by="price",ascending=False)
print(sorted_cars)

             car  company  year    price  mileage    Fuel  rating
4  toyota innova   toyota  2022  2200000       14   disel     4.6
6     kia seltos      kia  2024  1600000       16  petrol     4.5
1  hyundai creta  hyundai  2023  1500000       17   disel     4.3
0     honda city    honda  2022  1200000       18  petrol     4.5
3      tat nexon     tata  2023  1100000       19   disel     4.4
7  maruti baleno   maruti  2021   800000       22  petrol     4.1
2   maruti swift   maruti  2021   700000       23  petrol     4.2
5    honda amaze    honda  2020   650000       20  petrol     4.0

In [21]:
#calculate the average price
average_price=df["price"].mean()
print(average_price)

1218750.0

In [22]:
#find the maximum and minimum price
print("highest price:",df["price"].max())
print("highest price:",df["price"].min())

highest price: 2200000
highest price: 650000

In [23]:
df.describe()

              year         price    mileage    rating
count     8.000000  8.000000e+00   8.000000  8.000000
mean   2022.000000  1.218750e+06  18.625000  4.325000
std       1.309307  5.304563e+05   3.020761  0.212132
min    2020.000000  6.500000e+05  14.000000  4.000000
25%    2021.000000  7.750000e+05  16.750000  4.175000
50%    2022.000000  1.150000e+06  18.500000  4.350000
75%    2023.000000  1.525000e+06  20.500000  4.500000
max    2024.000000  2.200000e+06  23.000000  4.600000

In [24]:
#count cars by company
print(df["company"].value_counts())

company
honda      2
maruti     2
hyundai    1
tata       1
toyota     1
kia        1
Name: count, dtype: int64

In [27]:
#find fuel types
print(df["Fuel"].unique())

['petrol' 'disel']

In [28]:
df.isnull().sum()

car        0
company    0
year       0
price      0
mileage    0
Fuel       0
rating     0
dtype: int64

In [30]:
sample=pd.DataFrame({
    "car":["honda","tata","maruti","hyundai"],
    "price":[1200000,None,700000,1500000],
    "mileage":[18,19,None,17]
})
print(sample)

       car      price  mileage
0    honda  1200000.0     18.0
1     tata        NaN     19.0
2   maruti   700000.0      NaN
3  hyundai  1500000.0     17.0

In [31]:
sample["price"]=sample["price"].fillna(
    sample["price"].mean()
)
sample["mileage"]=sample["mileage"].fillna(
    sample["mileage"].mean()
)
print(sample)

       car         price  mileage
0    honda  1.200000e+06     18.0
1     tata  1.133333e+06     19.0
2   maruti  7.000000e+05     18.0
3  hyundai  1.500000e+06     17.0

In [32]:
df=df.drop_duplicates()
df

             car  company  year    price  mileage    Fuel  rating
0     honda city    honda  2022  1200000       18  petrol     4.5
1  hyundai creta  hyundai  2023  1500000       17   disel     4.3
2   maruti swift   maruti  2021   700000       23  petrol     4.2
3      tat nexon     tata  2023  1100000       19   disel     4.4
4  toyota innova   toyota  2022  2200000       14   disel     4.6
5    honda amaze    honda  2020   650000       20  petrol     4.0
6     kia seltos      kia  2024  1600000       16  petrol     4.5
7  maruti baleno   maruti  2021   800000       22  petrol     4.1