In [ ]:
import pandas as pd
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import LabelEncoder

In [ ]:
import pandas as pd
df=pd.read_csv("/content/pima-indians-diabetes.csv")
df

      6  148  72  35    0  33.6  0.627  50  1
0     1   85  66  29    0  26.6  0.351  31  0
1     8  183  64   0    0  23.3  0.672  32  1
2     1   89  66  23   94  28.1  0.167  21  0
3     0  137  40  35  168  43.1  2.288  33  1
4     5  116  74   0    0  25.6  0.201  30  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
762  10  101  76  48  180  32.9  0.171  63  0
763   2  122  70  27    0  36.8  0.340  27  0
764   5  121  72  23  112  26.2  0.245  30  0
765   1  126  60   0    0  30.1  0.349  47  1
766   1   93  70  31    0  30.4  0.315  23  0

[767 rows x 9 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = {} #CREATE EMPTY DICTIONARY
df_enc = df.copy() # here we just cop our original data
for col in df.columns: # it convert into the text using loop through of the column
    le[col] = LabelEncoder()  # now create new label for curent data
    df_enc[col] = le[col].fit_transform(df[col])

In [ ]:
df_enc

      6  148  72  35    0  33.6  0.627  50  1
0     1   23  19  22    0    62    196  10  0
1     8  121  17   0    0    30    367  11  1
2     1   27  19  16   62    77     53   0  0
3     0   75   4  28  102   209    513  12  1
4     5   54  23   0    0    53     80   9  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
762  10   39  25  41  108   118     55  42  0
763   2   60  21  20    0   155    187   6  0
764   5   59  22  16   71    58    115   9  0
765   1   64  14   0    0    95    195  26  1
766   1   31  21  24    0    98    169   2  0

[767 rows x 9 columns]

In [ ]:
 #features nd target
X = df_enc[['6', '148', '72', '35', '0', '33.6', '0.627', '50']]
y = df_enc['1']

In [ ]:
x

      6  148  72  35    0  33.6  0.627  50
0     1   23  19  22    0    62    196  10
1     8  121  17   0    0    30    367  11
2     1   27  19  16   62    77     53   0
3     0   75   4  28  102   209    513  12
4     5   54  23   0    0    53     80   9
..   ..  ...  ..  ..  ...   ...    ...  ..
762  10   39  25  41  108   118     55  42
763   2   60  21  20    0   155    187   6
764   5   59  22  16   71    58    115   9
765   1   64  14   0    0    95    195  26
766   1   31  21  24    0    98    169   2

[767 rows x 8 columns]

In [ ]:
y

0      0
1      1
2      0
3      1
4      0
      ..
762    0
763    0
764    0
765    1
766    0
Name: 1, Length: 767, dtype: int64

In [ ]:
from sklearn.naive_bayes import CategoricalNB

model = CategoricalNB()
model.fit(x, y)

CategoricalNB()

In [ ]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(x)
print(f"TrainingAccuracy: {accuracy_score(y,y_pred)*100:.2f}%")

TrainingAccuracy: 92.70%